### ISSUE TITLE
Missing on Press This

### ISSUE THREAD

**Issue by MichaelArestad** [Ipstenu/fauxgo#1]
Not sure if this is you or something I need to fix. Will look into later.

![image](https://cloud.githubusercontent.com/assets/1123119/7307486/79e8a01c-e9ca-11e4-89dd-6a6264118db5.png)

**Comment by Ipstenu** [comment]
I'm not sure why it's not being called either. My best bet is the enqueue isn't being summoned properly but I've not been able to untangle it :(

**Comment by MichaelArestad** [comment]
:dancers:
